apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deployer
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cicd-deployer-role
  namespace: dev
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cicd-deployer-binding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: cicd-deployer
    namespace: dev
roleRef:
  kind: Role
  name: cicd-deployer-role
  apiGroup: rbac.authorization.k8s.io
